version: '3.8'

services:
  llmsrv:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - MODEL=/models/Llama-3.2-8B-Instruct.Q8_0.gguf
      - N_CTX=8192
      - N_BATCH=512
    volumes:
      - /home/joseph/models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
