version: '3.8'

services:
  llmsrv:
    build:
      context: .
    restart: unless-stopped
    environment:
      - MODEL=/models/Llama-3.2-8B-Instruct.Q8_0.gguf
      - N_CTX=8192
      - N_BATCH=512
    volumes:
      - /home/joseph/models:/models
    labels:
      - "traefik.enable=true"
        # echo $(htpasswd -nB user) | sed -e s/\\$/\\$\\$/g
      - "traefik.http.middlewares.llmsrv-auth.basicauth.users=${TRAEFIK_AUTH}"
      - "traefik.http.routers.llmsrv.rule=Host(`llmsrv.hirsch.ee`)"
      - "traefik.http.routers.llmsrv.middlewares=llmsrv-auth@docker"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  traefik:
     external: true
